# Generated by Django 2.2.3 on 2019-07-28 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vendedor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=60)),
                ('endereco', models.CharField(max_length=150)),
                ('telefone', models.CharField(max_length=11)),
                ('idade', models.IntegerField()),
                ('email', models.CharField(max_length=60)),
                ('cpf', models.CharField(max_length=11)),
                ('plano_comissao', models.IntegerField()),
            ],
        ),
    ]
